site_name: NPoco Documentation
site_description: Documentation for NPoco

repo_url: https://github.com/schotime/NPoco
repo_name: NPoco

theme: readthedocs

docs_dir: gobblin-docs
extra_css: [css/extra.css]

pages:
    - Home: index.md
    - Getting Started: getting-started.md
    - User Guide:
        - Job Configuration Files: test.md
        - Deployment: test2.md
    

