site_name: NPoco Documentation
site_description: Documentation for NPoco

repo_url: https://github.com/schotime/NPoco
repo_name: NPoco

theme: readthedocs

docs_dir: docs
extra_css: [css/extra.css]

pages:
    - Home: index.md
    - Getting Started: getting-started.md
    - User Guide:
        - Mapping: mapping.md
        - Mapping Nested Objects: mapping-nested.md
    

